### ISSUE TITLE
Unrecognised Server

### ISSUE THREAD

**Issue by MnM001** [bp2008/blueirisviewer#3]
I get this error running BI 5.8.0.1

> 2023/10/03 09:46:26 An exception has occurred in class org.brian.blueirisviewer.util.Utilities:
> Error writing to server
> Additional Info:
> URL: http://192.168.0.179:80/json
> java.io.IOException: Error writing to server
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
> 	at org.brian.blueirisviewer.util.Utilities.getViaHttpConnection(Utilities.java:162)
> 	at org.brian.blueirisviewer.util.Utilities.getViaHttpConnection(Utilities.java:57)
> 	at org.brian.blueirisviewer.util.Utilities.getStringViaHttpConnection(Utilities.java:259)
> 	at org.brian.blueirisviewer.images.Images$1.run(Images.java:163)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.io.IOException: Error writing to server
> 	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at org.brian.blueirisviewer.util.Utilities.getViaHttpConnection(Utilities.java:158)
> 	... 4 more
> 
> 2023/10/03 09:46:26 An exception has occurred in class org.brian.blueirisviewer.images.Images$1:
> Exception message was null
> Unexpected token END OF FILE at position 0.
> 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
> 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
> 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
> 	at org.brian.blueirisviewer.images.Images$1.run(Images.java:167)
> 	at java.lang.Thread.run(Unknown Source)
>

**Comment by bp2008** [comment]
I have no idea what could be wrong.  This program still runs fine for me on BI 5.8.0.1.

Anyway I no longer maintain this program since I don't use it anymore.

**Comment by MnM001** [comment]
In case you are interested in fixing it - 2.8 works.
2.8.1 doesnt

Its a great program to quickly open and see whats happening. Better than opening a browser (in my opinion).

**Comment by MnM001** [comment]
Discard the above.
All versions work.
In my instance I had it in a folder called BIViewer
It just didnt like running in that folder!!
I renamed the folder and started working fine (2.8.1)

Not sure why it didnt like the original folder name anymore.

**Comment by bp2008** [comment]
That is weird.

I'm glad you found a solution.
